# Generated by Django 5.1.4 on 2024-12-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "preview",
                    models.ImageField(blank=True, null=True, upload_to="preview/"),
                ),
                ("video_url", models.URLField(verbose_name="Ссылка на видео")),
                ("description", models.TextField()),
            ],
            options={
                "verbose_name": "курс",
                "verbose_name_plural": "курсы",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="Урок", max_length=255, verbose_name="Название урока"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание урока/")),
                (
                    "preview",
                    models.ImageField(
                        default="lessons/previews/lesson.png",
                        upload_to="lessons/previews/",
                    ),
                ),
                ("video_url", models.URLField(verbose_name="Ссылка на видео")),
            ],
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата подписки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
