# Generated by Django 5.1.4 on 2024-12-27 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0003_alter_lesson_options_lesson_owner_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={},
        ),
        migrations.AlterModelOptions(
            name="subscription",
            options={},
        ),
        migrations.RemoveField(
            model_name="course",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="course",
            name="video_url",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="created_at",
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(verbose_name="Описание курса"),
        ),
        migrations.AlterField(
            model_name="course",
            name="name",
            field=models.CharField(
                default="Курс", max_length=255, verbose_name="Название курса"
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                default="courses/previews/course.png", upload_to="courses/previews/"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(verbose_name="Описание урока/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="name",
            field=models.CharField(
                default="Урок", max_length=255, verbose_name="Название урока"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                default="lessons/previews/lesson.png", upload_to="lessons/previews/"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="courses.course"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
